# Generated by Django 3.1.3 on 2021-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='date_end',
            field=models.CharField(max_length=5),
        ),
    ]
