# Generated by Django 3.1.3 on 2021-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcardapp', '0002_auto_20210702_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='date_end',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number_card',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='cards',
            name='serial',
            field=models.CharField(max_length=90),
        ),
    ]
